
name: Trigger Repos

on:
  #workflow_run: 
  #  workflows: [pages-build-deployment]
  #  types:
  #    - completed
  #  branches: [main, master]
    
  workflow_dispatch:
  
jobs:
  trigger_Pages_Publish_in_other_Repo:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}  # scopes token to whole org

          
      - name: A254
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/ch-sz-geo/A254/dispatches \
            -d '{"event_type":"update-design","client_payload":{"ref":"main"}}'    

- name: TEST
  env:
    GH_TOKEN: "${{ steps.generate-token.outputs.token }}"
  run: |
    curl -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer $GH_TOKEN" \
      https://api.github.com/repos/TEST/dispatches \
      -d '{"event_type":"update-design","client_payload":{"ref":"main"}}'
